include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.iconfig.dart'
    - '**/*.config.dart'
    - lib/**/i18n/*.*
    - lib/**/calendar/*.*
  errors:
    avoid_print: error
    avoid_returning_null: error
    avoid_returning_this: error
    avoid_unnecessary_containers: error
    unnecessary_lambdas: error
    unnecessary_statements: error
    unnecessary_overrides: error
    directives_ordering: error
    empty_catches: error
    lines_longer_than_80_chars: error
    prefer_final_in_for_each: error
    prefer_foreach: error
    prefer_function_declarations_over_variables: error
    prefer_final_locals: error
    avoid_returning_null_for_future: ignore
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    empty_statements: error
    prefer_void_to_null: error
    always_declare_return_types: error
    avoid_init_to_null: error
    avoid_return_types_on_setters: error
    avoid_returning_null_for_void: error
    await_only_futures: error
    file_names: error
    library_names: error
    always_put_control_body_on_new_line: error
    cascade_invocations: error
    prefer_single_quotes: error
    unnecessary_await_in_return: error
    parameter_assignments: error
    avoid_void_async: error
    prefer_collection_literals: error
    prefer_interpolation_to_compose_strings: error
    prefer_if_null_operators: error
    prefer_typing_uninitialized_variables: error
    unnecessary_parenthesis: error
    avoid_bool_literals_in_conditional_expressions: error
    avoid_annotating_with_dynamic: error
    annotate_overrides: error
    overridden_fields: error
    sort_child_properties_last: error
    prefer_int_literals: error
    always_put_required_named_parameters_first: error
    avoid_single_cascade_in_expression_statements: error
    non_constant_identifier_names: error
    prefer_final_fields: error
    omit_local_variable_types: ignore
    unnecessary_this: ignore
linter:
  rules:
    - avoid_print
    - avoid_returning_null
    - avoid_returning_this
    - avoid_unnecessary_containers
    - unnecessary_lambdas
    - unnecessary_statements
    - unnecessary_overrides
    - directives_ordering
    - empty_catches
    - prefer_final_in_for_each
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - empty_statements
    - prefer_void_to_null
    - always_declare_return_types
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - await_only_futures
    - file_names
    - library_names
    - always_put_control_body_on_new_line
    - cascade_invocations
    - prefer_single_quotes
    - unnecessary_await_in_return
    - prefer_expression_function_bodies
    - prefer_final_locals
    - parameter_assignments
    - avoid_void_async
    - prefer_collection_literals
    - prefer_interpolation_to_compose_strings
    - prefer_if_null_operators
    - prefer_typing_uninitialized_variables
    - unnecessary_parenthesis
    - lines_longer_than_80_chars
    - avoid_bool_literals_in_conditional_expressions
    - avoid_annotating_with_dynamic
    - annotate_overrides
    - overridden_fields
    - sort_child_properties_last
    - prefer_int_literals
    - always_put_required_named_parameters_first
    - avoid_single_cascade_in_expression_statements
    - non_constant_identifier_names
    - prefer_final_fields
    - omit_local_variable_types